package com.lingcloud.models;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

@Entity
@Table(name = "taskapiinfo")
public class TaskApiInfo {


  // ==============
  // PRIVATE FIELDS
  // ==============
  // An autogenerated id (unique for each user in the db)
  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  private long taskId;
  // The user email
  @NotNull
  private String taskName;
  // The user name
  @NotNull
  private String description;
  
  private byte frequency;
  
  private byte status;
  private int createTime;
  private int updateTime;
  private byte currentStatus;
  
  // ==============
  // PUBLIC METHODS
  // ==============
  public TaskApiInfo() { }
  
  public TaskApiInfo(long id) {
    this.taskId = id;
  }
  
  public long getTaskId() {
      return this.taskId;
  }  
  
  public String getTaskName() {
      return this.taskName;
  }
  
  public void setTaskName(String taskName) {
  	this.taskName = taskName;
  }

  // Getter and setter methods
  // ...
} // class User

/*

mysql> desc task_base_info;
+------------------+--------------+------+-----+---------+----------------+
| Field            | Type         | Null | Key | Default | Extra          |
+------------------+--------------+------+-----+---------+----------------+
| task_id          | int(10)      | NO   | PRI | NULL    | auto_increment | 
| account_id       | int(10)      | NO   | MUL | NULL    |                | 
| task_user_id     | int(10)      | NO   |     | NULL    |                | 
| class_id         | int(10)      | YES  |     | NULL    |                | 
| task_name        | varchar(64)  | NO   |     | NULL    |                | 
| description      | varchar(256) | YES  |     | NULL    |                | 
| frequency        | tinyint(2)   | NO   |     | NULL    |                | 
| alert_retry_num  | tinyint(2)   | NO   |     | NULL    |                | 
| alert_frequency  | tinyint(2)   | NO   |     | 0       |                | 
| is_snapshot      | tinyint(1)   | NO   |     | NULL    |                | 
| normal_monitor   | varchar(128) | NO   |     | NULL    |                | 
| mobile_monitor   | varchar(128) | NO   |     | NULL    |                | 
| request_num      | int(11)      | NO   |     | 0       |                | 
| api_request_info | text         | YES  |     | NULL    |                | 
| init_var_info    | text         | YES  |     | NULL    |                | 
| alert_threshold  | text         | YES  |     | NULL    |                | 
| status           | tinyint(1)   | NO   |     | 1       |                | 
| create_time      | int(10)      | NO   |     | NULL    |                | 
| update_time      | int(10)      | NO   |     | 0       |                | 
| current_status   | tinyint(1)   | NO   |     | 1       |                | 
+------------------+--------------+------+-----+---------+----------------+

*/